# ref: https://jupyterbook.org/en/stable/customize/config.html

title: Inequality vs Political Parties
author: Matt Arcillo
execute:
  execute_notebooks: force

bibtex_bibfiles:
  - LitMaps.bib

sphinx:
  config:
    bibtex_reference_style: author_year
