# ref: https://jupyterbook.org/en/stable/customize/config.html

title: Political Parties Affect on Inequality in the Federal Government
author: Matt Arcillo
execute:
  execute_notebooks: force

bibtex_bibfiles:
  - references.bib

sphinx:
  config:
    bibtex_reference_style: author_year
